# 베이스 이미지 설정
FROM python:3.10

# 작업 디렉토리 설정
WORKDIR /app

# 필요한 파일 복사
COPY train.py /app/train.py
COPY model/cifar_net.pth /app/model/cifar_net.pth

# 필요한 패키지 설치
RUN pip install torch torchvision

# 실행 명령어 설정
CMD ["python", "train.py"]
