# 베이스 이미지 설정
FROM python:3.9-slim

# 작업 디렉토리 설정
WORKDIR /app

# 필요한 파일 복사
COPY recognition.py /app
COPY cifar_net.pth /app

# 필요한 패키지 설치
RUN pip install torch torchvision pillow

# 컨테이너 실행 시 실행할 명령어
CMD [ "python", "recognition.py" ]
